server:
  port: 9000
dubbo:
  application:
    id: dubbo_account_provider
    name: dubbo_account_provider
  registry:
    address: zookeeper://62.234.80.253:2181
#    address: zookeeper://localhost:2181
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://62.234.80.253:2181
#    address: zookeeper://localhost:2181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmily_fx1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz@WSX

