spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=UTC&useSSL=false
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari 连接池配置
    hikari:
      # 最小空闲链接
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  aop:
    proxy-target-class: true

  shardingsphere:
    datasource:
      names: ds0,ds1

spring.shardingsphere.datasource.ds0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name: com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds0.url: jdbc:mysql://localhost:3306/ds0
spring.shardingsphere.datasource.ds0.username: root
spring.shardingsphere.datasource.ds0.password: 1qaz@WSX

spring.shardingsphere.datasource.ds1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name: com.mysql.jdbc.Driver
spring.shardingsphere.datasource.ds1.url: jdbc:mysql://localhost:3306/ds1
spring.shardingsphere.datasource.ds1.username: root
spring.shardingsphere.datasource.ds1.password: 1qaz@WSX

spring.shardingsphere.sharding.default-database-strategy.inline.sharding-column: member_id
spring.shardingsphere.sharding.default-database-strategy.inline.algorithm-expression: ds$->{member_id % 2}

spring.shardingsphere.sharding.tables.oms_order.actual-data-nodes: ds$->{0..1}.oms_order_$->{0..15}
spring.shardingsphere.sharding.tables.oms_order.table-strategy.inline.sharding-column: id
spring.shardingsphere.sharding.tables.oms_order.table-strategy.inline.algorithm-expression: oms_order_$->{id % 16}


server:
  port: 8090

#集成mybatis
mybatis:
  #xml路径
  mapper-locations: classpath:mapper/**.xml
  #pojo路径
  type-aliases-package: com.prayerlaputa.sharding.mapper
  configuration:
    #驼峰
    map-underscore-to-camel-case: true